version: "3.8"

services:
  # Service Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: facturly_backend
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
    networks:
      - facturly_net

  # Service Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: facturly_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next # <-- LIGNE IMPORTANTE : préserve le dossier .next du conteneur
    # ON CHANGE LA COMMANDE DE DÉMARRAGE ICI
    command: npm run dev
    networks:
      - facturly_net

  # Service Base de données (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: facturly_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - facturly_net

networks:
  facturly_net:
    driver: bridge

volumes:
  pgdata:
