version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: facturly-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
