[build]
  # Répertoire de base pour le build
  base = "frontend/"
  
  # Commande de build simple
  command = "npm install && npm run build"
  
  # Répertoire de publication
  publish = "out"

[build.environment]
  # Version de Node.js
  NODE_VERSION = "18"
  
  # Variables d'environnement pour le build
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "https://factur-ly.com/api"

# Redirections pour les routes dynamiques Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Configuration pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les images
[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les chunks JavaScript
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"