[build]
  # Répertoire de base pour le build
  base = "frontend"
  
  # Commande de build
  command = "npm run build"
  
  # Répertoire de publication (où se trouvent les fichiers buildés)
  publish = ".next"

[build.environment]
  # Version de Node.js à utiliser
  NODE_VERSION = "18"
  
  # Variables d'environnement pour le build
  NEXT_TELEMETRY_DISABLED = "1"

# Configuration pour Next.js avec App Router
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirections pour les routes dynamiques Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Configuration des headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuration pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"