[build]
cmd = "npm install && npm run build"

[deploy]
cmd = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"